version: "3.1"
services:

  database:
    image: "postgres"
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dg
      PGDATA: /var/lib/postgresql/data
    restart: always

  migration-app:
    image: "liquibase/liquibase"
    build:
      context: ./migration
    entrypoint: ["/wait-for-it.sh", "database:5432", "--", "/liquibase/liquibase_run.sh"]
    depends_on:
      - database
    links:
      - database

  backend-app:
    image: my-springboot-app
    build:
      context: ./backend
    depends_on:
      - database